# can do rolling update with zero downtime. 
#kubectl rollout status deployement webapp ------- to get the current status of deployement. 
# kubectl rollout history deployment deployementname
# going to previous revision -----  kubectl rollout undo deploy webapp --to-revision=2
# or just one rollout back ------ kubectl rollout undo deploy webapp 

# can do rolling update with zero downtime. 
#kubectl rollout status deployement webapp ------- to get the current status of deployement. 
#kubectl port-forward service/deployment-webapp 30083:83
#localhost:30083
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-dep
spec:
  # modify replicas according to your case
  minReadySeconds: 30 # How much time after pod has been created we show it in a ready state. I.e after 30 seconds when pod create it come into ready state. 
  replicas: 5
  selector:
    matchLabels:
      app: webapp-dep
  template:
    metadata:
      labels:
        app: webapp-dep
    spec:
      containers:
      - name: webapp-dep
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0
