#Deploy image  richardchesterwood/k8s-fleetman-queue
# running on port 8161 is the admin console 
#user and pass (admis/admin)
# expose nordport on 30010 
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1
