#service does not need matchlabels in selector but replicaset needs
#selector is in spec section and matches with spec section of pods. 
# this repicaset is managing pods which have lable app:webapp 

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-rs
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
