# First we will add lable 
# Put label in pod as  app: queue 
# use selector in service as app:webapp 
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
     #THis defines which services are going to be represented by this service 
     # THis service becomes a network end point for either other services
     #Or may be external user like browser.  
    app: queue
  ports:
    - name: http
      protocol: TCP
      port: 80
      #target port is contianer port, Port is service port mostly same both part This is clusterIP  service Means only inside the cluster not webbrowser. 
      #But our is webapp so we need NodePort service. NOdeport is 30000 to 327000
      targetPort: 80
      nodePort: 30080
  type: NodePort    #internet facing 
