#Image richardchesterwood/k8s-fleetman-api-gateway:release1
# expose port 8080 to the cluster 
#can test this port with / 
#Sam env varibles as before. 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  # modify replicas according to your case
  minReadySeconds: 30 # How much time after pod has been created we show it in a ready state. I.e after 30 seconds when pod create it come into ready state. 
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: richardchesterwood/k8s-fleetman-api-gateway:release1
        env: 
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
     #THis defines which services are going to be represented by this service 
     # THis service becomes a network end point for either other services
     #Or may be external user like browser.  
    app: api-gateway
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30020

  type: NodePort    #internet facing 
