apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker
spec:
  # modify replicas according to your case
  minReadySeconds: 30 # How much time after pod has been created we show it in a ready state. I.e after 30 seconds when pod create it come into ready state. 
  replicas: 1
  selector:
    matchLabels:
      app: position-tracker
  template:
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
      - name: position-tracker
        image: richardchesterwood/k8s-fleetman-position-tracker:release1
        env: 
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice
