#kubectl port-forward svc/fleetman-position-tracker 30020:8080
#http://localhost:30020/vehicles/City Truck

apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
     #THis defines which services are going to be represented by this service 
     # THis service becomes a network end point for either other services
     #Or may be external user like browser.  
    app: position-tracker
  ports:
    - name: http
      protocol: TCP
      port: 8080
      #target port is contianer port, Port is service port mostly same both part This is clusterIP  service Means only inside the cluster not webbrowser. 
      #But our is webapp so we need NodePort service. NOdeport is 30000 to 327000
      nodePort: 30020

  type: NodePort    #internet facing 
